name: teacher_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.6+2
  provider: ^4.0.4
  flutter_rating_bar: ^3.0.1+1
  horizontal_data_table: ^1.0.5+1
  http: ^0.12.0+4
  custom_switch: ^0.0.1
  lite_rolling_switch: ^0.1.1
  font_awesome_flutter: ^8.8.1
  flutter_datetime_picker: ^1.3.5
  intl: ^0.16.1
  table_calendar: ^2.2.3
  video_player: ^0.10.10
  webview_flutter: ^0.3.21
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  image_picker: ^0.6.6+1
  dash_chat: ^1.0.18
  syncfusion_flutter_gauges: ^18.1.48
  nima: ^1.0.5
  charts_flutter: ^0.9.0
  agora_rtc_engine: ^1.0.12
  permission_handler: ^5.0.0+hotfix.6
  diagonal_scrollview: ^0.1.0
  flutter_youtube: ^2.0.0
  multi_image_picker: ^4.6.7
  file_picker: ^1.9.0+1
  videos_player: ^0.1.3
  chewie: ^0.9.10
  flutter_launcher_icons: ^0.7.5
  path_provider: ^1.6.10
  sound_stream: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/check_attendance.png
    - assets/images/give_rewards.png
    - assets/images/write_remarks.png
    - assets/images/upcoming_exams.png
    - assets/images/track_schoolbus.png
    - assets/images/contact_parents.png
    - assets/images/student_profile.png
    - assets/images/premark.png
    - assets/images/classroom.png
    - assets/images/update_homework.png
    - assets/images/update_testpaper.png
    - assets/images/approve_leave.png
    - assets/images/leave_request.png
    - assets/images/logo.jpg
    - assets/images/school.jpg
    - assets/images/rachel.png
    - assets/images/sir.jpg
    - assets/images/child.jpg
    - assets/images/calendar.jpg
    - assets/images/tutorial.jpg
    - assets/images/tutorial2.jpg
    - assets/images/tutorial3.jpg
    - assets/videos/smartschool.mp4
    - assets/animations/superman-podium.nma
    - assets/animations/superman-podium.png
    - assets/images/report.png
    - assets/images/360.png
    - assets/images/1001.jpg
    - assets/images/raise_hand.png
    - assets/images/digi_campus_logo.png
    - assets/images/school_logo.jpeg
    - assets/images/virtual.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-bold.ttf

    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  adaptive_icon_background: "assets/images/launcher_bg.png"
  adaptive_icon_foreground: "assets/images/launcher_fg.png"
