class TimeTable{

  getTeacherTimeTable(String teacherCode){
    print(teacherCode);
    List<Map<String, dynamic>> teacherTimeTableList = new List<Map<String, dynamic>>();
//    teacherCode = 'AS';
    timeTableList.forEach((t) {

//      print(t['teacherCode']);
      if(t['teacherCode'].toString().compareTo(teacherCode)==0){
        print(teacherCode);
        teacherTimeTableList.add(t);
      }
    });

    return teacherTimeTableList;
  }

  static final List<Map<String, dynamic>> timeTableList = [
    {
      'teacherCode':'AS',
      'day': 'Monday',
      'subject':'English',
      'periods': [{'pdno': 1, 'class': 8},
        {'pdno': 2, 'class': 0,},
        {'pdno': 3, 'class': 0,}],
    },
    {
      'day': 'Tuesday',
      'teacherCode':'AS',
      'subject':'English',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 10, },
        {'pdno': 3, 'class': 8, }],
    },
    {
      'day': 'Wednesday',
      'teacherCode':'AS',
      'subject':'English',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 9},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Thursday',
      'teacherCode':'AS',
      'subject':'English',
      'periods': [{'pdno': 1, 'class': 9},
        {'pdno': 2, 'class': 10},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Friday',
      'teacherCode':'AS',
      'subject':'English',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 10}],
    },
    {
      'teacherCode':'ASP',
      'day': 'Monday',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 9},
        {'pdno': 2, 'class': 0,},
        {'pdno': 3, 'class': 0,}],
    },
    {
      'day': 'Tuesday',
      'teacherCode':'ASP',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0, },
        {'pdno': 3, 'class': 0, }],
    },
    {
      'day': 'Wednesday',
      'teacherCode':'ASP',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 10},
        {'pdno': 3, 'class': 9}],
    },
    {
      'day': 'Thursday',
      'teacherCode':'ASP',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Friday',
      'teacherCode':'ASP',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'teacherCode':'VV',
      'day': 'Monday',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 10},
        {'pdno': 2, 'class': 0,},
        {'pdno': 3, 'class': 0,}],
    },
    {
      'day': 'Tuesday',
      'teacherCode':'VV',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0, },
        {'pdno': 3, 'class': 0, }],
    },
    {
      'day': 'Wednesday',
      'teacherCode':'VV',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Thursday',
      'teacherCode':'VV',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Friday',
      'teacherCode':'VV',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 10},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 9}],
    },
    {
      'teacherCode':'RK',
      'day': 'Monday',
      'subject':'Malayalam',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 8,},
        {'pdno': 3, 'class': 0,}],
    },
    {
      'day': 'Tuesday',
      'teacherCode':'RK',
      'subject':'Malayalam',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 8, },
        {'pdno': 3, 'class': 0, }],
    },
    {
      'day': 'Wednesday',
      'teacherCode':'RK',
      'subject':'Malayalam',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Thursday',
      'teacherCode':'RK',
      'subject':'Malayalam',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 8},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Friday',
      'teacherCode':'RK',
      'subject':'Malayalam',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'teacherCode':'TK',
      'day': 'Monday',
      'subject':'Social',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 9,},
        {'pdno': 3, 'class': 10,}],
    },
    {
      'day': 'Tuesday',
      'teacherCode':'TK',
      'subject':'Social',
      'periods': [{'pdno': 1, 'class': 10},
        {'pdno': 2, 'class': 0, },
        {'pdno': 3, 'class': 0, }],
    },
    {
      'day': 'Wednesday',
      'teacherCode':'TK',
      'subject':'Social',
      'periods': [{'pdno': 1, 'class': 8},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Thursday',
      'teacherCode':'TK',
      'subject':'Social',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 10}],
    },
    {
      'day': 'Friday',
      'teacherCode':'TK',
      'subject':'Social',
      'periods': [{'pdno': 1, 'class': 9},
        {'pdno': 2, 'class': 8},
        {'pdno': 3, 'class': 0}],
    },
    {
      'teacherCode':'DM',
      'day': 'Monday',
      'subject':'Physics',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0,},
        {'pdno': 3, 'class': 9,}],
    },
    {
      'day': 'Tuesday',
      'teacherCode':'DM',
      'subject':'Physics',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 9, },
        {'pdno': 3, 'class': 10, }],
    },
    {
      'day': 'Wednesday',
      'teacherCode':'DM',
      'subject':'Physics',
      'periods': [{'pdno': 1, 'class': 10},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Thursday',
      'teacherCode':'DM',
      'subject':'Physics',
      'periods': [{'pdno': 1, 'class': 8},
        {'pdno': 2, 'class': 9},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Friday',
      'teacherCode':'DM',
      'subject':'Physics',
      'periods': [{'pdno': 1, 'class': 8},
        {'pdno': 2, 'class': 9},
        {'pdno': 3, 'class': 0}],
    },
    {
      'teacherCode':'SK',
      'day': 'Monday',
      'subject':'Malayalam',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 10,},
        {'pdno': 3, 'class': 0,}],
    },
    {
      'day': 'Tuesday',
      'teacherCode':'SK',
      'subject':'Malyalam',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0, },
        {'pdno': 3, 'class': 9, }],
    },
    {
      'day': 'Wednesday',
      'teacherCode':'SK',
      'subject':'Malayalam',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Thursday',
      'teacherCode':'SK',
      'subject':'Malayalam',
      'periods': [{'pdno': 1, 'class': 10},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 9}],
    },
    {
      'day': 'Friday',
      'teacherCode':'SK',
      'subject':'Malayalam',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },

    {
      'teacherCode':'RR',
      'day': 'Monday',
      'subject':'IT',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0,},
        {'pdno': 3, 'class': 8,}],
    },
    {
      'day': 'Tuesday',
      'teacherCode':'RR',
      'subject':'IT',
      'periods': [{'pdno': 1, 'class': 9},
        {'pdno': 2, 'class': 0, },
        {'pdno': 3, 'class': 0, }],
    },
    {
      'day': 'Wednesday',
      'teacherCode':'RR',
      'subject':'IT',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 10}],
    },
    {
      'day': 'Thursday',
      'teacherCode':'RR',
      'subject':'IT',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Friday',
      'teacherCode':'RR',
      'subject':'IT',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'teacherCode':'TS',
      'day': 'Monday',
      'subject':'Biology',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0,},
        {'pdno': 3, 'class': 0,}],
    },
    {
      'day': 'Tuesday',
      'teacherCode':'TS',
      'subject':'Biology',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0, },
        {'pdno': 3, 'class': 0, }],
    },
    {
      'day': 'Wednesday',
      'teacherCode':'TS',
      'subject':'Biology',
      'periods': [{'pdno': 1, 'class': 9},
        {'pdno': 2, 'class': 8},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Thursday',
      'teacherCode':'TS',
      'subject':'Biology',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Friday',
      'teacherCode':'TS',
      'subject':'Biology',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 10},
        {'pdno': 3, 'class': 8}],
    },
    {
      'day': 'Monday',
      'teacherCode':'DB',
      'subject':'Geography',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0, },
        {'pdno': 3, 'class': 0, }],
    },

    {
      'day': 'Tuesday',
      'teacherCode':'DB',
      'subject':'Geography',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0, },
        {'pdno': 3, 'class': 0, }],
    },
    {
      'day': 'Wednesday',
      'teacherCode':'DB',
      'subject':'Geography',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 8}],
    },
    {
      'day': 'Thursday',
      'teacherCode':'DB',
      'subject':'Geography',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Friday',
      'teacherCode':'DB',
      'subject':'Geography',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Monday',
      'teacherCode':'HP',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0, },
        {'pdno': 3, 'class': 0, }],
    },

    {
      'day': 'Tuesday',
      'teacherCode':'HP',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 8},
        {'pdno': 2, 'class': 0, },
        {'pdno': 3, 'class': 0, }],
    },
    {
      'day': 'Wednesday',
      'teacherCode':'HP',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
    {
      'day': 'Thursday',
      'teacherCode':'HP',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 8}],
    },
    {
      'day': 'Friday',
      'teacherCode':'HP',
      'subject':'Maths',
      'periods': [{'pdno': 1, 'class': 0},
        {'pdno': 2, 'class': 0},
        {'pdno': 3, 'class': 0}],
    },
  ];
}